name: base_de_projet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4

  #Firebase
  cloud_firestore: ^4.15.8
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  
  #Code
  dartz: ^0.10.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.10
  injectable: ^2.3.2
  encrypt: ^5.0.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1 #Annotation pour Freezed
  kt_dart: ^1.1.0 #Fonction de Kotlin
  get_it: ^7.6.7
  provider: ^6.1.2
  rxdart: ^0.27.7
  uuid: ^4.3.3 #Crypt
  #shared_preference

  #UI
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1 #Pour faire glisser des éléments et faire apparaitres des boutons supprimer / modifier
  intl: ^0.18.1 #Internationnal pour les formats de date / format de nombre
  implicitly_animated_reorderable_list: ^0.4.2 #Liste réordonnalbe
  easy_sidemenu: ^0.5.0 #Menu à gauche
  flutter_signin_button: ^2.0.0 #Bouton Google / Facebook / Apple ...
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0 #Texte qui prend la bonne taille
  gap: ^3.0.1
  feedback: ^3.0.1

  #Autre
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^5.0.1 #Récupère les numéros de version de l'app (1.0.0-12)
  dartdoc: ^8.0.6
  flutter_email_sender: ^6.0.2
  path_provider: ^2.1.2
  flutter_widget_from_html_core: ^0.14.11
  awesome_notifications_core: ^0.8.1
  awesome_notifications: any
  permission_handler: ^11.3.0
  cloud_functions: ^4.6.8


dev_dependencies:
  build_runner: ^2.4.8 #Génère du code automatiquement
  connectivity_plus: ^5.0.2 #Test la connexion internet de l'appareil
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.3.0 #Règles pour un code propre
  test: ^1.21.4
  auto_route_generator: ^7.3.2
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  #color: "#42a5f5"
  background_image: "assets/splash.png"

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/logo_vide.png
    - config/
    - assets/administratif/a_propos_de_l_application.html
    - assets/administratif/condtition_utilisation.html