name: base_de_projet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.29
  auto_route: ^5.0.1
  cloud_firestore: ^3.4.7
  cupertino_icons: ^1.0.5
  dartz: ^0.10.0-nullsafety.2
  encrypt: ^5.0.1
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  implicitly_animated_reorderable_list: ^0.4.2
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  kt_dart: ^0.10.0
  package_info_plus: ^1.4.3+1
  provider: ^6.0.3
  rxdart: ^0.27.5
  uuid: ^3.0.6
  flutter_signin_button: ^2.0.0
  easy_sidemenu: ^0.3.1
  ansicolor: ^2.0.1


dev_dependencies:
  build_runner: ^2.2.0
  connectivity_plus: ^2.3.6+1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  lint: ^1.10.0
  test: ^1.21.4
  auto_route_generator: ^5.0.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  #color: "#42a5f5"
  background_image: "assets/splash.png"

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/logo_vide.png
    - config/
  