name: base_de_projet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_route: ^7.4.0

  #Firebase
  cloud_firestore: ^4.8.1
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  google_sign_in: ^6.1.4
  flutter:
    sdk: flutter
  
  #Code
  dartz: ^0.10.0-nullsafety.2
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.3.4
  injectable: ^2.1.2
  encrypt: ^5.0.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0 #Annotation pour Freezed
  kt_dart: ^1.1.0 #Fonction de Kotlin
  get_it: ^7.6.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  uuid: ^3.0.7 #Crypt
  #shared_preference

  #UI
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.5
  flutter_slidable: ^3.0.0 #Pour faire glisser des éléments et faire apparaitres des boutons supprimer / modifier
  intl: ^0.17.0 #Internationnal pour les formats de date / format de nombre
  implicitly_animated_reorderable_list: ^0.4.2 #Liste réordonnalbe
  easy_sidemenu: ^0.4.1+1 #Menu à gauche
  flutter_signin_button: ^2.0.0 #Bouton Google / Facebook / Apple ...
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0 #Texte qui prend la bonne taille

  #Autre
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^4.0.2 #Récupère les numéros de version de l'app (1.0.0-12)
  dartdoc: ^6.2.2


dev_dependencies:
  build_runner: ^2.3.3 #Génère du code automatiquement
  connectivity_plus: ^4.0.1 #Test la connexion internet de l'appareil
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  lint: ^1.10.0 #Règles pour un code propre
  test: ^1.21.4
  auto_route_generator: ^7.1.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  #color: "#42a5f5"
  background_image: "assets/splash.png"

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/logo_vide.png
    - config/