// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgGBWvlUyGJLZIBC78dEDCTFMmsCPFAc',
    appId: '1:881913570091:web:cf108faa3269e067f31b6e',
    messagingSenderId: '881913570091',
    projectId: 'base-de-projet',
    authDomain: 'base-de-projet.firebaseapp.com',
    storageBucket: 'base-de-projet.appspot.com',
    measurementId: 'G-FF61Z7MPZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwFNdspQ3ty8P4BUvDf5Ru6NAi6hoqpgU',
    appId: '1:881913570091:android:f5761b7850ceda84f31b6e',
    messagingSenderId: '881913570091',
    projectId: 'base-de-projet',
    storageBucket: 'base-de-projet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVCbILlEKyRVB9KRceloMGKZQwmLDII0',
    appId: '1:881913570091:ios:7f13dcce7f1bece0f31b6e',
    messagingSenderId: '881913570091',
    projectId: 'base-de-projet',
    storageBucket: 'base-de-projet.appspot.com',
    iosClientId: '881913570091-tdljncqp6ko5tck80f9lg0qd309e36cc.apps.googleusercontent.com',
    iosBundleId: 'com.alban.basedeprojet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWVCbILlEKyRVB9KRceloMGKZQwmLDII0',
    appId: '1:881913570091:ios:5d80f0e0dfb16562f31b6e',
    messagingSenderId: '881913570091',
    projectId: 'base-de-projet',
    storageBucket: 'base-de-projet.appspot.com',
    iosClientId: '881913570091-f44bbcv7drnai9u4tkcdubjdslgbck3m.apps.googleusercontent.com',
    iosBundleId: 'com.alban.baseDeProjet',
  );
}
